routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.'
    ],
    function ()
    {
        Route::group(
            [
                'middleware' => 'auth',
            ],
            function () {
                Route::get(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.get', 'uses' => 'UserController@getNewPassword']
                );
                Route::post(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.post', 'uses' => 'UserController@postNewPassword']
                );
                Route::resource('user', 'UserController', ['except' => 'delete']);
                Route::resource('permissions', 'PermissionsController');
                Route::resource('roles', 'RolesController');

                //products
                Route::post('product/{id}/ajax_field','ProductController@ajaxFieldChange')->middleware('ajax')->name('product.ajax_field');
                Route::resource('product', 'ProductController');

                // translations
                Route::get(
                    'translation/{group}',
                    ['as' => 'translation.index', 'uses' => 'TranslationController@index']
                );
                Route::post(
                    'translation/{group}',
                    ['as' => 'translation.update', 'uses' => 'TranslationController@update']
                );
            });


        Route::get('login', 'AuthController@showLoginForm')->name('login');
        Route::post('login', 'AuthController@login');
        Route::post('logout', 'AuthController@logout')->name('logout');
        Route::get('/','HomeController@index')->name('home');
    }
);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index');

app/Models/Product.php
<?php

namespace App\Models;


use App\Models\Traits\MetaGettable;
use App\Models\Traits\PositionSortedTrait;
use App\Models\Traits\VisibleTrait;
use App\Models\Traits\WithTranslationsTrait;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use function PHPUnit\Framework\at;

class Product extends Model
{
    use Translatable;
    use VisibleTrait;
    use MetaGettable;
    use WithTranslationsTrait;
    use PositionSortedTrait;

    //use Searchable;

    public $translatedAttributes = [
        'title',
        'short_description',
        'description',
        'meta_title',
        'meta_keywords',
        'meta_description',
    ];

    /**
     * @var array
     */
    protected $fillable = [
        'slug',
        'position',
        'status',
        'image',
        'price',
        'count',
    ];

    /*public function toSearchableArray(): array
    {
        $array = $this->toArray();

        unset($array['image']);

        unset($array['guid']);

        return $array;
    }*/

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function main_categories(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attribute_product() {
        return $this->hasMany(AttributeProduct::class, 'product_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function sale(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Sale::class,'sale_products','product_id','sale_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ProductImages::class);
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Api\v1\Events\Product\Create as ProductCreateEvent;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\AjaxFieldsChangerTrait;
use App\Http\Requests\Backend\Product\ProductCreateRequest;
use App\Http\Requests\Backend\Product\ProductUpdateRequest;
use App\Models\Attribute;
use App\Models\AttributeProduct;
use App\Models\Category;
use App\Models\PackType;
use App\Models\Product;
use App\Models\ProductImages;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    use AjaxFieldsChangerTrait;

    public $module = "product";

    public function index(Request $request)
    {
        abort_unless(\Gate::allows($this->module . '_access'), 403);

        if ($request->get('draw')) {
            $list = Product::joinTranslations()->select(
                'products.id',
                'product_translations.title',
                'position',
                'status',
                'is_popular',
                'image',
                'price',
            );
            return $this->_datatable($list);
        }

        return view('admin.view.'.$this->module .'.index');
    }

    public function create()
    {
        abort_unless(\Gate::allows($this->module . '_create'), 403);

        $data['module'] = $this->module;

        $data['model'] = new Product();

        return view('admin.view.'.$this->module .'.create',$data);
    }

    public function store(ProductCreateRequest $request)
    {
        abort_unless(\Gate::allows($this->module . '_create'), 403);

        $url = $this->save_image($request,'image');

        $input = $request->all();

        $input['image'] = $url;

        $model = new Product($input);

        $model->save();

        toastr()->success(__('admin_labels.success.add',['model' => ucfirst($this->module)]));

        return redirect()->route('admin.'.$this->module .'.index');
    }

    public function edit(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_edit'), 403);

        $model = Product::findOrFail($product->id);

        $data['module'] = $this->module;

        $data['model'] = $model;

        return view('admin.view.'.$this->module .'.edit',$data);
    }

    public function update(ProductUpdateRequest $request, Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_edit'), 403);

        $model = Product::findOrFail($product->id);

        $input = $request->all();

        if((!$request->hasFile('image') && $product->image != null)){

            $input['image'] = $product->image;
        }else{
            $url = $this->save_image($request,'image');

            $input['image'] = $url;
        }

        $model->update($input);

        toastr()->success(__('admin_labels.success.update',['model' => ucfirst($this->module)]));

        return redirect()->route('admin.'.$this->module .'.index');
    }

    public function show(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_show'), 403);

        $this->edit($product);

    }

    public function destroy(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_delete'), 403);

        $product->delete();

        toastr()->success(__('admin_labels.success.delete',['model' => ucfirst($this->module)]));

        return back();
    }

    private function _datatable(Builder $list)
    {
        return $dataTables = DataTables::of($list)
            ->filterColumn(
                'id',
                function ($query, $keyword) {
                    $query->whereRaw("products.id like ?", ["%{$keyword}%"]);
                })
            ->filterColumn(
                'title',
                function ($query, $keyword) {
                    $query->whereRaw("product_translations.title like ?", ["%{$keyword}%"]);
                })
            ->editColumn(
                'status',
                function ($model) {
                    return view(
                        'datatables.toggler',
                        ['model' => $model, 'type' => $this->module, 'field' => 'status']
                    )->render();
                }
            )
            ->editColumn(
                'image',
                function ($model) {
                    return view('admin.partials.image',
                        ['src'=>$model->image]
                    )->render();
                }
            )
            ->addColumn(
                'actions',
                function ($model) {
                    return view(
                        'datatables.control_buttons',
                        ['model' => $model, 'front_link' => true, 'type' => $this->module]
                    )->render();
                }
            )
            ->rawColumns(['status','image', 'actions'])
            ->make();
    }
}

resources/views/admin/view/product/create.blade.php
@extends('admin.layouts.editable')

@section('assets.top')
    @parent
    <script src="{!! asset('assets/components/sysTranslit/js/jquery.synctranslit.min.js') !!}"></script>
@stop

@section('content')
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            {!! Form::model($model, array('enctype'=>'multipart/form-data','route' => 'admin.product.store','class' => 'form-horizontal')) !!}

                @include('admin.view.' . $module . '.partials._form')

            {!! Form::close() !!}
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@stop

resources/views/admin/view/product/edit.blade.php
@extends('admin.layouts.editable')

@section('assets.top')
    @parent
    <script src="{!! asset('assets/components/sysTranslit/js/jquery.synctranslit.min.js') !!}"></script>
@stop

@section('content')

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            	{!! Form::model($model, array('enctype'=>'multipart/form-data','method' => 'put', 'class' => 'form-horizontal', 'route' => array('admin.product.update', $model->id))) !!}
            @include('admin.view.' . $module . '.partials._form')
            	{!! Form::close() !!}
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@stop

resources/views/admin/view/product/index.blade.php
@extends('admin.layouts.listable')
@section('content_header')

    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.product.create') }}">
                {{__('admin_labels.add_product')}}
            </a>
        </div>
    </div>

@stop
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="pages-table">
                        {!!
                            TablesBuilder::create(
                                ['id' => "datatable1", 'class' => "table table-bordered table-striped table-hover"]
                            )->addHead([
                                    ['text' => trans('admin_labels.id')],
                                    ['text' => trans('admin_labels.image')],
                                    ['text' => trans('admin_labels.title')],
                                    ['text' => trans('admin_labels.visible')],
                                    ['text' => trans('admin_labels.position')],
                                    ['text' => trans('admin_labels.price')],
                                    ['text' => trans('admin_labels.actions')],
                                ])
                                ->addFoot([
                                    ['attr' => ['colspan' => 7]]
                                ])

                             ->makehtml()
                        !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
    {!!
                           TablesBuilder::create(
                                ['id' => "datatable1", 'class' => "table table-bordered table-striped table-hover"],

                                [
                                    'bStateSave' => true,
                                    'order' => [[ 0, 'desc' ]],
                                    "columns" => [
                                        [ "data" => "id" ],
                                        [ "data" => "image"],
                                        [ "data" => "title"],
                                        [ "data" => "status" ],
                                        [ "data" => "position" ],
                                        [ "data" => "price" ],
                                        [ "data" => "actions" ],
                                    ],
                                ]
                            )
                             ->makejs()
                        !!}

@endsection