routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.'
    ],
    function ()
    {
        Route::group(
            [
                'middleware' => 'auth',
            ],
            function () {
                Route::get(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.get', 'uses' => 'UserController@getNewPassword']
                );
                Route::post(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.post', 'uses' => 'UserController@postNewPassword']
                );
                Route::resource('user', 'UserController', ['except' => 'delete']);
                Route::resource('permissions', 'PermissionsController');
                Route::resource('roles', 'RolesController');

                //products
                Route::post('product/{id}/ajax_field','ProductController@ajaxFieldChange')->middleware('ajax')->name('product.ajax_field');
                Route::resource('product', 'ProductController');

                // translations
                Route::get(
                    'translation/{group}',
                    ['as' => 'translation.index', 'uses' => 'TranslationController@index']
                );
                Route::post(
                    'translation/{group}',
                    ['as' => 'translation.update', 'uses' => 'TranslationController@update']
                );
            });


        Route::get('login', 'AuthController@showLoginForm')->name('login');
        Route::post('login', 'AuthController@login');
        Route::post('logout', 'AuthController@logout')->name('logout');
        Route::get('/','HomeController@index')->name('home');
    }
);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index');

app/Models/Product.php
<?php

namespace App\Models;


use App\Models\Traits\MetaGettable;
use App\Models\Traits\PositionSortedTrait;
use App\Models\Traits\VisibleTrait;
use App\Models\Traits\WithTranslationsTrait;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use function PHPUnit\Framework\at;

class Product extends Model
{
    use Translatable;
    use VisibleTrait;
    use MetaGettable;
    use WithTranslationsTrait;
    use PositionSortedTrait;

    //use Searchable;

    public $translatedAttributes = [
        'title',
        'short_description',
        'description',
        'meta_title',
        'meta_keywords',
        'meta_description',
    ];

    /**
     * @var array
     */
    protected $fillable = [
        'slug',
        'position',
        'status',
        'image',
        'price',
        'count',
    ];

    /*public function toSearchableArray(): array
    {
        $array = $this->toArray();

        unset($array['image']);

        unset($array['guid']);

        return $array;
    }*/

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function main_categories(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function attribute_product() {
        return $this->hasMany(AttributeProduct::class, 'product_id','id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function sale(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Sale::class,'sale_products','product_id','sale_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function images(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(ProductImages::class);
    }
}

app/Http/Controllers/Backend/ProductController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Api\v1\Events\Product\Create as ProductCreateEvent;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\AjaxFieldsChangerTrait;
use App\Http\Requests\Backend\Product\ProductCreateRequest;
use App\Http\Requests\Backend\Product\ProductUpdateRequest;
use App\Models\Attribute;
use App\Models\AttributeProduct;
use App\Models\Category;
use App\Models\PackType;
use App\Models\Product;
use App\Models\ProductImages;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    use AjaxFieldsChangerTrait;

    public $module = "product";

    public function index(Request $request)
    {
        abort_unless(\Gate::allows($this->module . '_access'), 403);

        if ($request->get('draw')) {
            $list = Product::joinTranslations()->select(
                'products.id',
                'product_translations.title',
                'position',
                'status',
                'is_popular',
                'image',
                'price',
            );
            return $this->_datatable($list);
        }

        return view('admin.view.'.$this->module .'.index');
    }

    public function create()
    {
        abort_unless(\Gate::allows($this->module . '_create'), 403);

        $data['module'] = $this->module;

        $data['model'] = new Product();

        return view('admin.view.'.$this->module .'.create',$data);
    }

    public function store(ProductCreateRequest $request)
    {
        abort_unless(\Gate::allows($this->module . '_create'), 403);

        $url = $this->save_image($request,'image');

        $input = $request->all();

        $input['image'] = $url;

        $model = new Product($input);

        $model->save();

        toastr()->success(__('admin_labels.success.add',['model' => ucfirst($this->module)]));

        return redirect()->route('admin.'.$this->module .'.index');
    }

    public function edit(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_edit'), 403);

        $model = Product::findOrFail($product->id);

        $data['module'] = $this->module;

        $data['model'] = $model;

        return view('admin.view.'.$this->module .'.edit',$data);
    }

    public function update(ProductUpdateRequest $request, Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_edit'), 403);

        $model = Product::findOrFail($product->id);

        $input = $request->all();

        if((!$request->hasFile('image') && $product->image != null)){

            $input['image'] = $product->image;
        }else{
            $url = $this->save_image($request,'image');

            $input['image'] = $url;
        }

        $model->update($input);

        toastr()->success(__('admin_labels.success.update',['model' => ucfirst($this->module)]));

        return redirect()->route('admin.'.$this->module .'.index');
    }

    public function show(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_show'), 403);

        $this->edit($product);

    }

    public function destroy(Product $product)
    {
        abort_unless(\Gate::allows($this->module . '_delete'), 403);

        $product->delete();

        toastr()->success(__('admin_labels.success.delete',['model' => ucfirst($this->module)]));

        return back();
    }

    private function _datatable(Builder $list)
    {
        return $dataTables = DataTables::of($list)
            ->filterColumn(
                'id',
                function ($query, $keyword) {
                    $query->whereRaw("products.id like ?", ["%{$keyword}%"]);
                })
            ->filterColumn(
                'title',
                function ($query, $keyword) {
                    $query->whereRaw("product_translations.title like ?", ["%{$keyword}%"]);
                })
            ->editColumn(
                'status',
                function ($model) {
                    return view(
                        'datatables.toggler',
                        ['model' => $model, 'type' => $this->module, 'field' => 'status']
                    )->render();
                }
            )
            ->editColumn(
                'image',
                function ($model) {
                    return view('admin.partials.image',
                        ['src'=>$model->image]
                    )->render();
                }
            )
            ->addColumn(
                'actions',
                function ($model) {
                    return view(
                        'datatables.control_buttons',
                        ['model' => $model, 'front_link' => true, 'type' => $this->module]
                    )->render();
                }
            )
            ->rawColumns(['status','image', 'actions'])
            ->make();
    }
}

resources/views/admin/view/product/tabs/general.blade.php
 <div class="form-group">
            <label for="image" class="col-sm-2 control-label">
                {!! Form::label('image', trans('admin_labels.image'), array('class' => "control-label")) !!}
            </label>
            <div class="col-xs-12 col-sm-7 col-md-10 col-lg-3">
                <div id="upload_div" style="display: flex; flex-direction: row-reverse;justify-content: flex-end;">
                    @if(isset($model->image))
                        <label id="delete_image" class="delete_image" style="color: red; display: block; margin-left: 10px;"
                               data-id="{!! $model->id !!}"
                               data-token="{!! csrf_token() !!}"
                               data-field="image"
                               data-url="{!! route('admin.product.ajax_field', ['id' => $model->id]) !!}"
                               data-value=''>
                            X
                        </label>
                    @endif
                    <img id="img" src="{{isset($model->image)?$model->image:asset('storage/images/upload_image.png')}}"
                         class="img-thumbnail mb-1 lg-1">
                </div>
                <input id = "input_image" class="input-file" type="file" name="image" accept="image/*">
            </div>
        </div>

<div class="form-group">
    <label for="slug" class="col-sm-2 control-label">
        {!! Form::label('slug', __('admin_labels.slug'), array('class' => "control-label")) !!}
    </label>

    <div class="col-sm-10">
        <div class="col-xs-6">
            {!! Form::text('slug', $model->slug, array('placeholder' => __('admin_labels.slug'), 'class' => 'form-control input-sm')) !!}
        </div>
        {!! $errors->first('slug', '<span class="error">:message</span>') !!}
        <br>
        <p>
            <button type="button"
                    class="btn btn-success btn-sm slug-generate">{!! __('admin_labels.buttons.generate') !!}</button>
        </p>
    </div>
</div>

        <div class="form-group">
            <label for="status" class="col-sm-2 control-label">
                {!! Form::label('status', __('admin_labels.status'), array('class' => "control-label")) !!}
            </label>

            <div class="col-sm-10">
                <div class="col-xs-2">
                    {!! Form::select('status', array("1" => __('admin_labels.visible'), "0" => __('admin_labels.no_visible')), $model->status, array('class' => 'form-control col-xs-1')) !!}
                </div>
                {!! $errors->first('status', '<span class="error">:message</span>') !!}
            </div>
        </div>

<div class="form-group">
    <label for="position" class="col-sm-2 control-label">
        {!! Form::label('position', __('admin_labels.position'),array('class' => "control-label")) !!}
    </label>

    <div class="col-sm-10">
        <div class="col-xs-1">
            {!! Form::text('position', $model->position ? $model->position : 0, array('placeholder' => __('admin_labels.position'), 'class' => 'form-control input-sm')) !!}
        </div>
        {!! $errors->first('position', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="price" class="col-sm-2 control-label">
        {!! Form::label('price', __('admin_labels.price'), array('class' => "control-label")) !!}
    </label>

    <div class="col-sm-10">
        <div class="col-xs-6">
            {!! Form::number('price', $model->price, array('placeholder' => __('admin_labels.price'),'step' => 0.1, 'class' => 'form-control input-sm')) !!}
        </div>
        {!! $errors->first('price', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="count" class="col-sm-2 control-label">
        {!! Form::label('count', __('admin_labels.count'), array('class' => "control-label")) !!}
    </label>

    <div class="col-sm-10">
        <div class="col-xs-6">
            {!! Form::number('count', $model->count, array('placeholder' => __('admin_labels.count'),'step' => 1, 'class' => 'form-control input-sm')) !!}
        </div>
        {!! $errors->first('count', '<span class="error">:message</span>') !!}
    </div>
</div>

resources/views/admin/view/product/tabs/locale.blade.php
<div class="form-group">
    <label for="{!! $locale . '[title]' !!}" class="col-sm-2 control-label">
        {!! Form::label($locale.'[title]', __('admin_labels.title'), array('class' => "control-label")) !!}
    </label>

    <div class="col-xs-6">
        {!! Form::text($locale.'[title]', isset($model->translate($locale)->title) ? $model->translate($locale)->title : '', array('placeholder' => __('admin_labels.title'), 'class' => 'form-control input-sm name_'.$locale)) !!}
        {!! $errors->first($locale.'.title', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="{!! $locale . '[description]' !!}" class="col-sm-2 control-label">
        {!! Form::label($locale.'[description]', __('admin_labels.description'), array('class' => "control-label")) !!}
    </label>

    <div class="col-xs-6">
        {!! Form::textarea( $locale.'[description]', isset($model->translate($locale)->description) ? $model->translate($locale)->description : '', array('placeholder' => __('admin_labels.description'), 'class' => 'form-control ckeditor', 'rows' => '5')) !!}
        {!! $errors->first($locale.'.description', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="{!! $locale . '[meta_title]' !!}" class="col-sm-2 control-label">
        {!! Form::label($locale.'[meta_title]', __('admin_labels.meta_title'), array('class' => "control-label")) !!}
    </label>

    <div class="col-xs-6">
        {!! Form::text( $locale.'[meta_title]', isset($model->translate($locale)->meta_title) ? $model->translate($locale)->meta_title : '', array('placeholder' => __('admin_labels.meta_title'), 'class' => 'form-control input-sm')) !!}
        {!! $errors->first($locale.'.meta_title', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="{!! $locale . '[meta_keywords]' !!}" class="col-sm-2 control-label">
        {!! Form::label($locale.'[meta_keywords]', __('admin_labels.meta_keywords'), array('class' => "control-label")) !!}
    </label>

    <div class="col-xs-6">
        {!! Form::text( $locale.'[meta_keywords]', isset($model->translate($locale)->meta_keywords) ? $model->translate($locale)->meta_keywords : '', array('placeholder' => __('admin_labels.meta_keywords'), 'class' => 'form-control')) !!}
        {!! $errors->first($locale.'.meta_keywords', '<span class="error">:message</span>') !!}
    </div>
</div>

<div class="form-group">
    <label for="{!! $locale . '[meta_description]' !!}" class="col-sm-2 control-label">
        {!! Form::label($locale.'[meta_description]', __('admin_labels.meta_description'), array('class' => "control-label")) !!}
    </label>

    <div class="col-xs-6">
        {!! Form::textarea( $locale.'[meta_description]', isset($model->translate($locale)->meta_description) ? $model->translate($locale)->meta_description : '', array('placeholder' => __('admin_labels.meta_description'), 'class' => 'form-control ckeditor', 'rows' => '5')) !!}
        {!! $errors->first($locale.'.meta_description', '<span class="error">:message</span>') !!}
    </div>
</div>