routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.'
    ],
    function ()
    {
        Route::group(
            [
                'middleware' => 'auth',
            ],
            function () {
                Route::get(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.get', 'uses' => 'UserController@getNewPassword']
                );
                Route::post(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.post', 'uses' => 'UserController@postNewPassword']
                );
                Route::resource('user', 'UserController', ['except' => 'delete']);
                Route::resource('permissions', 'PermissionsController');
                Route::resource('roles', 'RolesController');

                //products
                Route::post('product/{id}/ajax_field','ProductController@ajaxFieldChange')->middleware('ajax')->name('product.ajax_field');
                Route::resource('product', 'ProductController');

                // translations
                Route::get(
                    'translation/{group}',
                    ['as' => 'translation.index', 'uses' => 'TranslationController@index']
                );
                Route::post(
                    'translation/{group}',
                    ['as' => 'translation.update', 'uses' => 'TranslationController@update']
                );
            });


        Route::get('login', 'AuthController@showLoginForm')->name('login');
        Route::post('login', 'AuthController@login');
        Route::post('logout', 'AuthController@logout')->name('logout');
        Route::get('/','HomeController@index')->name('home');
    }
);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index');

app/Models/Translation.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Translation model
 * @package App\Models
 */
class Translation extends Model
{
    
    /**
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'updated_at'];
    
    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param                                       $group
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOfTranslatedGroup($query, $group)
    {
        return $query->where('group', $group)->whereNotNull('value');
    }
    
    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param                                       $ordered
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOrderByGroupKeys($query, $ordered)
    {
        if ($ordered) {
            $query->orderBy('group')->orderBy('key');
        }
        
        return $query;
    }
    
    /**
     * @param \Illuminate\Database\Eloquent\Builder $query
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSelectDistinctGroup($query)
    {
        $select = '';
        
        switch (DB::getDriverName()) {
            case 'mysql':
                $select = 'DISTINCT `group`';
                break;
            default:
                $select = 'DISTINCT "group"';
                break;
        }
        
        return $query->select(DB::raw($select));
    }
    
}

app/Http/Controllers/Backend/TranslationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Classes\Meta;
use FlashMessages;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\TranslationUpdateRequest;
use App\Models\Translation;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;

class TranslationController extends Controller
{
    public $module = "translation";

    /**
     * @var array
     */
    public $locales = [];

    /**
     * TranslationController constructor.
     */
    public function __construct()
    {
        Meta::title(trans('labels.translations'));

        $this->getExistsLocales();
    }

    /**
     * @param string $group
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index($group)
    {
        abort_unless(\Gate::allows('translations_access'), 403);
        $page = request('page', 1);

        $list = $this->getGroupCollection($group);

        $total = $list->count();
        $list = $list->slice(($page - 1) * 50);

        $list = new LengthAwarePaginator(
            $list,
            $total,
            50,
            $page,
            [
                'path' => route('admin.' . $this->module . '.index', $group),
                'query' => [],
            ]
        );

        $data['locales'] = $this->locales;
        $data['list'] = $list;
        $data['group'] = $group;
        $data['page'] = $page;
        $data['page_title'] = trans('labels.translation_group_' . $group);
        $data['module'] = $this->module;

        request()->flush();

        return view('admin.view.' . $this->module . '.index', $data);
    }

    /**
     * @param \App\Http\Requests\Backend\TranslationUpdateRequest $request
     *
     * @return mixed
     */
    public function update(TranslationUpdateRequest $request)
    {
        $group = $request->route('group');

        $db_translations = Translation::where(['group' => $group])
            ->get();

        foreach ($this->locales as $locale) {
            $translations = $request->get($locale);

            $locale_exist_translations = $this->getLocaleExistTranslationsForGroup($locale, $group);
            $translation = array_merge($locale_exist_translations, $translations);

            foreach ($translation as $key => $value) {
                $_translation = $db_translations->where('key', $key)->where('locale', $locale)->first();

                if (!$_translation) {
                    $_translation = new Translation(['locale' => $locale, 'group' => $group, 'key' => $key]);
                }

                $_translation->value = $value;

                $_translation->save();
            }

            if (Cache::getStore() instanceof \Illuminate\Cache\TaggableStore) {
                cache()->tags('translations')->forget($locale . '_' . $group);
            }

        }
        toastr()->success(__('admin_labels.success.update',['model' => ucfirst($this->module)]));

        return redirect()->route('admin.' . $this->module . '.index', ['group' => $group, 'page' => $request->input('page', 1)])->with('success',trans('messages.save_ok'));
    }

    /**
     * fill array of all physical exists locales
     */
    public function getExistsLocales()
    {
        $this->locales = config('app.locales');
    }

    /**
     * @param string $group
     * @param string $locale
     *
     * @return Collection
     */
    private function getGroupCollection($group, $locale = null)
    {
        $locales = $locale ? [$locale] : $this->locales;

        $list = [];
        foreach ($locales as $locale) {
            $path = app()->langPath() . '/' . $locale . '/' . $group . '.php';
            $_file_list = Arr::dot(include($path));

            $_translation = Translation::whereLocale($locale)->whereGroup($group)
                ->get(['key', 'value'])
                ->keyBy('key');

            foreach ($_file_list as $key => $item) {
                $list[$key][$locale] = $_translation->has($key) ? $_translation->get($key)->value : $item;
            }

            $_db_list = Arr::except($_translation->toArray(), array_keys($_file_list));

            foreach ($_db_list as $key => $item) {
                $list[$key][$locale] = $item['value'];
            }
        }

        ksort($list);

        return Collection::make($list);
    }

    /**
     * @param string $locale
     * @param string $group
     *
     * @return array
     */
    private function getLocaleExistTranslationsForGroup($locale, $group)
    {
        $list = [];

        foreach ($this->getGroupCollection($group, $locale) as $key => $translation) {
            $list[$key] = isset($translation[$locale]) ? $translation[$locale] : '';
        }

        return $list;
    }
}

resources/views/admin/view/translation/index.blade.php
@extends('adminlte::page')

@section('content')
    @include('admin.partials.messages')
    <div class="row">
        <div class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="translations-table">

                        <form action="{!! route('admin.translation.update', $group) !!}" method="post" role="form"
                              class="without-js-validation">

                            {!! csrf_field() !!}

                            <input type="hidden" name="page" value="{!! $page !!}">

                            <table class="table table-bordered table-striped">
                                <tbody>
                                <tr>
                                    <td colspan="{!! count($locales) + 1 !!}">
                                        @include('admin.partials._buttons')
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="{!! count($locales) + 1 !!}">
                                        <div class="text-center">
                                            {!! $list->links() !!}
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                    <th style="width: 9%">{{__('admin_labels.key')}}</th>

                                    @foreach($locales as $locale)
                                        <th style="width: 13%">{!! trans('admin_labels.tab_' . $locale) !!}</th>
                                    @endforeach
                                </tr>
                                </tbody>

                                @foreach($list as $key => $items)
                                    <tr>
                                        <td>
                                            {!! $key !!}
                                        </td>

                                        @foreach($locales as $locale)
                                            <td class="form-group
                                            @if ($errors->has($locale.'.'.$key)) has-error @endif">
                                            <textarea rows="1" cols="1"
                                                    name="{!! $locale !!}[{!! $key !!}]"
                                                    id="{!! $locale !!}_{!! str_replace(' ', '_', $key) !!}"
                                                    class="form-control input-sm"
                                            >{!! isset($items[$locale]) ? $items[$locale] : null !!}</textarea>
                                            </td>
                                        @endforeach
                                    </tr>
                                @endforeach

                                <tr>
                                    <td colspan="{!! count($locales) + 1 !!}">
                                        <div class="text-center">
                                            {!! $list->links() !!}
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="{!! count($locales) + 1 !!}">
                                        @include('admin.partials._buttons')
                                    </td>
                                </tr>
                            </table>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@extends('admin.partials.style')