routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');
Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.'
    ],
    function ()
    {
        Route::group(
            [
                'middleware' => 'auth',
            ],
            function () {
                Route::get(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.get', 'uses' => 'UserController@getNewPassword']
                );
                Route::post(
                    'user/new_password/{id}',
                    ['as' => 'user.new_password.post', 'uses' => 'UserController@postNewPassword']
                );
                Route::resource('user', 'UserController', ['except' => 'delete']);
                Route::resource('permissions', 'PermissionsController');
                Route::resource('roles', 'RolesController');

                //products
                Route::post('product/{id}/ajax_field','ProductController@ajaxFieldChange')->middleware('ajax')->name('product.ajax_field');
                Route::resource('product', 'ProductController');

                // translations
                Route::get(
                    'translation/{group}',
                    ['as' => 'translation.index', 'uses' => 'TranslationController@index']
                );
                Route::post(
                    'translation/{group}',
                    ['as' => 'translation.update', 'uses' => 'TranslationController@update']
                );
            });


        Route::get('login', 'AuthController@showLoginForm')->name('login');
        Route::post('login', 'AuthController@login');
        Route::post('logout', 'AuthController@logout')->name('logout');
        Route::get('/','HomeController@index')->name('home');
    }
);

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index');

resources/views/admin/partials/_buttons.blade.php
<div class="row box-footer @if (!empty($class)) {!! $class !!} @endif">
    <div class="col-md-6">
        @if($module != 'translation')
        <a href="{!! empty($back_url) ? route('admin.' . $module . '.index') : $back_url !!}" class="btn btn-secondary">{{__('admin_labels.buttons.back')}}</a>
        @endif
    </div>

    <div class="col-md-6 justify-content-end text-right">
        <input class="btn btn-success btn-flat button" type="submit" value="{{__('admin_labels.buttons.save')}}">
        @if($module == 'user' && $model->id && !$without_password_change)
            <a href="{!! route('admin.user.new_password.get', $model->id) !!}" class="btn btn-warning margin-right-15 btn-flat">{!! trans("admin_labels.buttons.change_password") !!}</a>
        @endif

    </div>

</div>

resources/views/admin/partials/image.blade.php
@if (empty($attributes['width']))
    <?php $attributes['width'] = 50; ?>
@endif

@if (empty($attributes['height']))
    <?php $attributes['height'] = $attributes['width']; ?>
@endif

<img src="{!! thumb($src, $attributes['width'], $attributes['height']) !!}"
    @if (!empty($attributes) && count($attributes))
        @foreach($attributes as $key => $value)
            {!! $key !!}="{!! $value !!}"
        @endforeach
    @endif
/>

resources/views/admin/partials/messages.blade.php
<div class="message-container">
   {{-- @if ($messages->has('error'))
        @foreach ($messages->get('error') as $message)
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {!!$message!!}
            </div>
        @endforeach
    @endif

    @if ($messages->has('warning'))
        @foreach ($messages->get('warning') as $message)
            <div class="alert alert-dismissable alert-warning">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {!!$message!!}
            </div>
        @endforeach
    @endif

    @if ($messages->has('info'))
		@foreach ($messages->get('info') as $message)
			<div class="alert alert-dismissable alert-info">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
				{!!$message!!}
			</div>
		@endforeach
	@endif--}}

        @if ($message = Session::get('success'))
        <div class="alert alert-dismissable alert-default-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{$message}}
        </div>
	@endif
</div>

resources/views/admin/partials/style.blade.php
@push('css')
    {{--    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />--}}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet" />
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link href="{{ asset('themes/default/css/admin/adminltev3.css') }}" rel="stylesheet" />
    <link href="{{ asset('themes/default/css/admin/custom.css') }}" rel="stylesheet" />
    <link href="{{ asset('themes/default/css/admin/style.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    @toastr_css
@endpush
@push('js')
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.full.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.0/js/dataTables.select.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js"></script>
    <script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('themes/default/js/admin/app.min.js') }}"></script>
    {{--    <script>--}}
    {{--        $(document).on("product-images-selected", function(event, files) {--}}
    {{--            for(var iterator in files) {--}}
    {{--                $('#product-images-duplicator').find('a').click(); //create new instance of duplication row--}}

    {{--                var $tr = $('table.product-images tr.duplication-row:not(.duplicate)').last();--}}

    {{--                var $image_input = $tr.find('input[data-related-image]'),--}}
    {{--                    $image = $image_input.closest('div.form-group').find('img'),--}}
    {{--                    $position_input = $tr.find('input[name*="position"]'),--}}
    {{--                    image_path = '/' + files[iterator].path;--}}

    {{--                $image_input.val(image_path);--}}

    {{--                $image.attr('src', image_path);--}}

    {{--                $position_input.val($tr.index());--}}

    {{--            }--}}
    {{--        });--}}
    {{--    </script>--}}
    <script>
        (function() {
            'use strict';
            window.addEventListener('load', function() {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function(form) {
                    form.addEventListener('submit', function(event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
    @toastr_js
    @toastr_render
@endpush